### ISSUE TITLE
Release 1.0.0 as final or at least as beta to be production ready

### ISSUE THREAD

**Issue by mrsarm** [pierredavidbelanger/logback-awslogs-appender#12]
Previously I had to resolve the issue #11 to be able to use the latest version of this library, and the solution proposed for a non-production environment worked.

But for production environment, we release or code with continues delivery systems, that build the application from the code and prepare a release with Maven, with something like this:

    mvn release:prepare -B

The Maven `release` plugin doesn't allow to use SNAPSHOT versions of dependencies, so we got this error using the version `1.0.0-SNAPSHOT`:

    [ERROR] Failed to execute goal org.apache.maven.plugins:maven-release-plugin:2.5.3:prepare (default-cli) on project app-core: Can't release project due to non released dependencies :
    [ERROR] ca.pjer:logback-awslogs-appender:jar:1.0.0-SNAPSHOT:compile

We have to wait to much for the final version? Could you release a "beta" version?

**Comment by pierredavidbelanger** [comment]
I am not sure what I am waiting for. 

So lets call it 1.0.0 :)

I just made the release, it should be available in Maven Central in a couple of minutes.

**Comment by mrsarm** [comment]
Many thanks! The maven task worked with the release.
