### ISSUE TITLE
Consider adding KinesisFirehose 

### ISSUE THREAD

**Issue by nyilmaz** [pierredavidbelanger/logback-awslogs-appender#15]
Abstracting sending strategy, kinesis forehose client can be added as an alternative to cloudwatch.

**Comment by pierredavidbelanger** [comment]
I guess this is something you are better letting AWS manage for you:

See [Subscription Filters with Amazon Kinesis Data Firehose](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs//SubscriptionFilters.html#FirehoseExample), you achieve what you want and can use my lib as is.
