### ISSUE TITLE
log stream created as date_IS_UNDEFINED

### ISSUE THREAD

**Issue by bentatham** [pierredavidbelanger/logback-awslogs-appender#16]
I have configured the logStreamName as per the example:
```
    <logStreamName>apolloserver-${date}</logStreamName>
```
but when I look in cloudwatch logs, it creates the log stream as `apolloserver-date_IS_UNDEFINED`.

Any idea what is going on here?  Looking at the source here, I assume that the variable `${date}` is handled by AWS itself, and not by this library.  But is there something I need to do here?

**Comment by pierredavidbelanger** [comment]
Have a look at the [config example here](https://github.com/pierredavidbelanger/logback-awslogs-appender#more-configurations).

If you use a variable like `${date}`, you should define this key somewhere for the interpolation to work, this this:

```xml
...
    <!-- Timestamp used into the Log Stream Name -->
    <timestamp key="date" datePattern="yyyyMMdd"/>
...
```
