### ISSUE TITLE
Which logback appender to use?

### ISSUE THREAD

**Issue by graingert** [pierredavidbelanger/logback-awslogs-appender#2]
Currently there are a few:

@pierredavidbelanger https://github.com/pierredavidbelanger/logback-awslogs-appender
@kernspin https://github.com/brick-commerce/cloudwatch-logback-appender
@trautonen https://github.com/trautonen/logback-ext/tree/master/logback-ext-cloudwatch-appender
@tyutyutyu https://github.com/Bankmonitor/logback-appenders/

And they all seem reasonably active, it seems a shame to duplicate this effort

**Comment by pierredavidbelanger** [comment]
I see no shame.

Its a [less than 150 lines of code class](https://github.com/pierredavidbelanger/logback-awslogs-appender/blob/master/src/main/java/ca/pjer/logback/AwsLogsAppender.java). Not much of an effort here ;)

Just pick and choose the one that best fits your project :)
