### ISSUE TITLE
Resolve conflict between license in pom.xml and LICENSE

### ISSUE THREAD

**Issue by benjaminvulpes** [pierredavidbelanger/logback-awslogs-appender#22]
pom.xml calls out LGPL, but `LICENSE` file is GNU General Public License. Please advise as to which holds.

**Comment by pierredavidbelanger** [comment]
Oh, you are right.
Honestly I am not sure which one to choose.

I guess this kind of library calls more for LGPL. What do you think?

**Comment by benjaminvulpes** [comment]
I would vastly prefer LGPL; it would allow me to use this package in a distributed JAR without releasing the source of my own application.

**Comment by pierredavidbelanger** [comment]
ok, this is fix. anyways LGPL was clearly my initial choice, as per de pom.xml (witch is bundled with the jar iirc), I probably just made a mistake the day I created the repo and let github chose the license.

**Comment by benjaminvulpes** [comment]
Thank you very much, Pierre!
