### ISSUE TITLE
Release to Maven central

### ISSUE THREAD

**Issue by gdjennings** [pierredavidbelanger/logback-awslogs-appender#27]
Can you cut a release and publish to Maven Central with the log retention changes?

**Comment by pierredavidbelanger** [comment]
I am confused now, I thought [1.2.0](https://mvnrepository.com/artifact/ca.pjer/logback-awslogs-appender/1.2.0) contained the retention changes... 

I probably made a mistake and forgot to pull the latest change before releasing this one.

I will bump to 1.2.1 and release again, right now.

**Comment by pierredavidbelanger** [comment]
1.2.1 is on its way to maven central.
thank you for reporting this!
