### ISSUE TITLE
Specific another AWS access key id?

### ISSUE THREAD

**Issue by abcfy2** [pierredavidbelanger/logback-awslogs-appender#34]
I have multiple AWS account and I want to put logs into a different AWS cloudwatch, how to?

Thanks.

**Comment by pierredavidbelanger** [comment]
it seems [here](https://github.com/pierredavidbelanger/logback-awslogs-appender/blob/master/src/main/java/ca/pjer/logback/AWSLogsStub.java#L36) we rely implicitly on the [DefaultAWSCredentialsProviderChain](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/auth/DefaultAWSCredentialsProviderChain.html).

So, eihter you implicitly configure for logging and explicitly your main use case will use an other key, or you can send a PR to allow this lib to be explicitly configured.

**Comment by abcfy2** [comment]
OK. I try to commit a PR, please review. Thanks.

**Comment by pierredavidbelanger** [comment]
I bump the lib version to 1.6.0 and published to maven, it should be available in a couple of minutes.

Thank you for your contribution, it was really appreciated.
