### ISSUE TITLE
Log event too large: 267837 bytes exceeds limit of 262144

### ISSUE THREAD

**Issue by malkusch** [pierredavidbelanger/logback-awslogs-appender#6]
It seems Amazon has an undocumented limit of 262144 bytes per log event:

    com.amazonaws.services.logs.model.InvalidParameterException: Log event too large: 267837 bytes exceeds limit of 262144 (Service: AWSLogs; Status Code: 400; Error Code: InvalidParameterException; Request ID: xxx)
            at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1545)
            at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1183)
            at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:964)
            at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:676)
            at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:650)
            at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:633)
            at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$300(AmazonHttpClient.java:601)
            at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:583)
            at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:447)
            at com.amazonaws.services.logs.AWSLogsClient.doInvoke(AWSLogsClient.java:1685)
            at com.amazonaws.services.logs.AWSLogsClient.invoke(AWSLogsClient.java:1661)
            at com.amazonaws.services.logs.AWSLogsClient.putLogEvents(AWSLogsClient.java:1402)
            at ca.pjer.logback.AWSLogsStub.logPreparedEvents(AWSLogsStub.java:86)
            at ca.pjer.logback.AWSLogsStub.logEvents(AWSLogsStub.java:75)
            at ca.pjer.logback.AsyncWorker.flush(AsyncWorker.java:93)
            at ca.pjer.logback.AsyncWorker.run(AsyncWorker.java:75)

I suggest trimming too long events and adding a warning that the event was trimmed.

**Comment by malkusch** [comment]
In an experiment I was able to log an event with a message size of 262118 but not 262119 bytes. 262118 is 262144 - 26. Amazon [mentions those 26 bytes] for calculating the maximum batch size.

**Comment by pierredavidbelanger** [comment]
From your [comment here](https://github.com/pierredavidbelanger/logback-awslogs-appender/pull/3#issuecomment-337706944):

> Let's throw an IllegalArgumentException in setMaxBatchSize() if the batch size is not within 1 and 10000.

This will do the job for the maximum number of log events in a batch.

> What about the batch size? Requeueing (or discarding) the offending events and adding a warning to decrease the batch size might be an option.

I was thinking, maybe [here](https://github.com/pierredavidbelanger/logback-awslogs-appender/blob/master/src/main/java/ca/pjer/logback/AsyncWorker.java#L138), when we `queue.drainTo(events, maxBatchSize)`, instead of draining upto `maxBatchSize`, we could transfer one event at a time from the `queue` to the `events`, summing the size and stopping at a threshold.

**Comment by malkusch** [comment]
> instead of draining upto maxBatchSize, we could transfer one event at a time

This would simplify it a lot. There's however a chance of a performance trade off for this solution, as [`drainTo()` might be more efficient](https://docs.oracle.com/javase/9/docs/api/java/util/concurrent/BlockingQueue.html#drainTo-java.util.Collection-):

> This operation may be more efficient than repeatedly polling this queue.

Concretely that means, there will be a lock/unlock for each poll vs. only one lock/unlock for draining.

Personally I would prefer a simple solution, but without a benchmark it's hard to decide if this performance trade off might become significant.

**Comment by pierredavidbelanger** [comment]
> a chance of a performance trade off for this solution, as drainTo() might be more efficient

You are right about the performance (lock/unlock), but since this part runs in the background thread, I guess this is not a big deal. We will have to test it (though it may be hard to see any différence).

**Comment by pierredavidbelanger** [comment]
Also, sure, start a PR and get that T-Shirt :)

**Comment by malkusch** [comment]
> You are right about the performance (lock/unlock), but since this part runs in the background thread, I guess this is not a big deal.

Yes, that was also my first though, but locking/unlocking does unfortunately affect a logging thread as well.

**Comment by malkusch** [comment]
I made two further branches with a [polling implementation](https://github.com/malkusch/logback-awslogs-appender/compare/6-constraints...malkusch:6-poll-each?expand=1) and a [draining implementation](https://github.com/malkusch/logback-awslogs-appender/compare/6-constraints...malkusch:6-drain-and-requeue?expand=1). The latter is not complete yet, as it doesn't requeue offending events. However those two are sufficient two compare the prominent case when a batch would be less than 1MB.

I'll come back as soon as I made a reasonable comparison. But I do already prefere the polling implementation, just because it's little invasive.

**Comment by pierredavidbelanger** [comment]
Impressive work you have done here, thank you!

I too prefer the poling impl, for the simplicity of it.

I have two little comments:

I like your [SAFE_DRAIN_COUNT](https://github.com/malkusch/logback-awslogs-appender/blob/6-poll-each/src/main/java/ca/pjer/logback/AsyncWorker.java#L154) thing, it is a nice and simple optimisation.

[in this for loop](https://github.com/malkusch/logback-awslogs-appender/blob/6-poll-each/src/main/java/ca/pjer/logback/AsyncWorker.java#L157) I think we can, without problem, go beyond `i < maxBatchSize`, in fact we can go up to `i < 10000`. The user dont care how big the batches are, as long as we flush when we have `maxBatchSize` events in memory (I realize this is what I was trying yo say [here](https://github.com/pierredavidbelanger/logback-awslogs-appender/issues/8#issuecomment-338304519)).

**Comment by malkusch** [comment]
> in fact we can go up to i < 10000

I agree. It's there now.

**Comment by malkusch** [comment]
I did some JMH benchmarks and it appears that locking is not an issue at all. In fact the polling implementation wins over the draining implementation.

**Comment by malkusch** [comment]
Ok, I did some benchmarks with an AWSLogsStub mock of AsyncWorker.append(). So this is only comparing how lock contention affects a logging thread (i.e. how flushing of the worker affects a logging thread). In summary the draining implementation is superior. However only when there are many threads involved. The effect is even more increased with a higher maxBatchSize. The following plots are for maxBatchSize 50, 500 and 5000. The y-axis depicts the ratio drain/poll:

![50](https://user-images.githubusercontent.com/1623984/31861438-9893aea2-b72d-11e7-80a5-c94b265c738b.png)

![500](https://user-images.githubusercontent.com/1623984/31861445-a5f95b14-b72d-11e7-8520-780974c52c08.png)


![5000](https://user-images.githubusercontent.com/1623984/31861447-a8bb9a10-b72d-11e7-9997-662ebd5d6098.png)

So this clearly shows that during flushing, many logging threads are significantly affected by the worker thread. Still I don't know how much practical difference that might make. I still do prefere the polling implementation. The draining implementation is only finished half, and I fear that requeing is not such a trivial task. I'll have a look how requeing could be implemented with little invasive changes.

**Comment by malkusch** [comment]
The [draining implementation](https://github.com/malkusch/logback-awslogs-appender/compare/6-constraints...malkusch:6-drain-and-requeue?expand=1) is now finished with a direct requeing to the queue. There is no discard logic involved to keep requeuing simple. If the queue is full (which is a very rare event, as we drained a fair bit of it already) the event would be discarded. In a functional test I could see that requeued events did not mess up any order. CloudWatchLogs seems to maintain order between batches with the event's timestamp.

Given that It's actually no more invasive than the polling implementation plus it seems to be superior performance wise, I would now favour the draining implementation.

Decide which of both approaches suites you and I would merge it into this branch.

**Comment by pierredavidbelanger** [comment]
I kind of like (code wise) both approches now.

But, since they both are simple and your benchmarks seems to favour requeing, I will choose the requeing impl.
