### ISSUE TITLE
Rename maxBatchSize into e.g. maxBatchLogEvents

### ISSUE THREAD

**Issue by malkusch** [pierredavidbelanger/logback-awslogs-appender#8]
While implementing the polling approach (#6) I got myself confused over the namings. [Amazon's documentation](http://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_PutLogEvents.html) mentions:
- The **maximum batch size** is 1,048,576 bytes
- The **maximum number of log events** in a batch is 10,000

From that documentation I would think that [`maxBatchSize`](https://github.com/pierredavidbelanger/logback-awslogs-appender/blob/44d1030c6b0a522210705b339226fe94d94b4117/src/main/java/ca/pjer/logback/AwsLogsAppender.java#L66-L74) refers to the maximum size of a batch in bytes. We do however use `maxBatchSize` for the number of log events in a batch.  I suggest renaming `maxBatchSize` into e.g. `maxBatchLogEvents`.

As `maxBatchSize` is not yet released, renaming would be painless.

**Comment by pierredavidbelanger** [comment]
I am not sure about this one.
I guess we can keep the `maxBatchSize` separated from the `maxBatchLogEvents`.

I see `maxBatchSize` as kind of `maxBatchSizeBeforeFlushing`.
It a mesure of how quickly we want events to flush to AWS.

Then, when we flush, we can do so with batches of any size, as long as AWS supports it.

**Comment by pierredavidbelanger** [comment]
In fact, there is nothing that prevent us from sending greater batch to AWS, as long as, from the user perspective, the number of events in the buffer is never greater than `maxBatchSize` and the buffer never stay in memory for longer than `maxFlushTimeMillis`.

**Comment by malkusch** [comment]
Hmm, I'm not sure if we are talking about different things now. This is just about renaming `maxBatchSize` into something else without changing any behaviour. I suggest renaming that because Amazon uses "maximum batch size" for measuring bytes, while we use `maxBatchSize` for a number of elements. It just confused me and I guess it might confuse others as well. But if you think that's not an issue at all, please close this issue.

**Comment by pierredavidbelanger** [comment]
Oh, its only a semantic issue, ok. You are right, `maxBatchSize` really in fact means `maxBatchLogEvents`, so why not. Go for it.

We should wait after the merge of #7 for this though, just to bypass merge issues.

**Comment by malkusch** [comment]
> We should wait after the merge of #7 for this though, just to bypass merge issues.

Let's merge it now into master. I will rebase #7. In fact I want to have it there so that I can rename [`MAX_BATCH_BYTES`](https://github.com/malkusch/logback-awslogs-appender/blob/dc02932efc5e662ed122c48863f2ec619a2389a0/src/main/java/ca/pjer/logback/AsyncWorker.java#L148) into `MAX_BATCH_SIZE`.

**Comment by pierredavidbelanger** [comment]
I just merged #9 and, like you said, #7 will need a rebase.
